# Config file for automatic testing at travis-ci.org
language: python
os: linux
env: KERAS="keras==2.2.5"
jobs:
    include:
        # PyTorch versions
        - python: 3.7
          env: TORCH=torch==1.1.0 TV=torchvision==0.3.0
            TF=tensorflow==1.15.2 TFP="tensorflow-probability==0.7.0"
        - python: 3.7
          env: TORCH=torch==1.4.0 TV=torchvision==0.5.0
            TF=tensorflow==1.15.2 TFP="tensorflow-probability==0.7.0"
        - python: 3.7
          env: TORCH=torch==1.3.1+cpu TV=torchvision==0.4.2
            TF=tensorflow==1.15.2 TFP="tensorflow-probability==0.7.0"
        - python: 3.7
          env: TORCH=torch==1.2.0+cpu TV=torchvision==0.4.2
              KERAS="keras==2.2.5" TF=tensorflow==1.15.2 TFP="tensorflow-probability==0.7.0"
        # Tensorflow versions
        - python: 3.6
          env: TF="tensorflow==1.12.3" TFP="tensorflow-probability==0.5.0"
            TORCH=torch==1.3.1+cpu TV=torchvision==0.4.2
        - python: 3.6
          env: TF="tensorflow==1.13.2" TFP="tensorflow-probability==0.6.0"
            TORCH=torch==1.3.1+cpu TV=torchvision==0.4.2
        - python: 3.7
          env: TF="tensorflow==1.14.0" TFP="tensorflow-probability==0.7.0"
            TORCH=torch==1.3.1+cpu TV=torchvision==0.4.2
notifications:
  email: true

install:
  #code below copied from keras' .travis.yml
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  #  Pillow 7.0.0 break torchvision: https://github.com/pytorch/vision/issues/1712
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
        numpy pytest h5py nose Pillow=6.1.0
  - source activate test-environment
  - echo pip install $TF $TFP $KERAS $TORCH $TV
  - pip install -f https://download.pytorch.org/whl/torch_stable.html
        $TF $TFP $KERAS $TORCH $TV
  - pip install ".[dev, torch, tensorflow]"
  - KERAS_BACKEND=tensorflow
  # Useful for debugging
  - pip freeze
script:
  - ./run_tests.sh
